name: gym_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sa_multi_tween: ^1.1.1
  google_fonts: ^1.1.0
  simple_animations: ^2.2.1
  http: ^0.12.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/loginBackground.jpg
    - images/backgroundGymapp.jpg
    - images/signupbackground.jpg
    - images/profile.png
